### PR TITLE
Generate new WebP image if original file is modified since last time

### PR DESCRIPTION
**Pull request by BlueCocoa**
Generate new WebP image if original file is modified since last time

Signed-off-by: Cocoa <0xbbc@0xbbc.com>

### CODE REVIEW

**Comment by n0vad3v** [comment]
Nice PR, but there seems a little problem that the older converted images are not deleted after the change of the original image, this might cause a possible leakage of the original one's content.

**Comment by BlueCocoa** [comment]
The mentioned functionality looks good in my test. The code that I performed in the test is shown below.

My environment

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G103
$ go version
go version go1.13.4 darwin/amd64
```

```bash
cat <<EOF | sudo tee config.json
{
	"HOST": "127.0.0.1",
	"PORT": "3333",
	"QUALITY": "80",
	"IMG_PATH": "./pics",
	"ALLOWED_TYPES": ["jpg","png","jpeg"]
}
EOF
go build
./webp_server_go &
curl -H "User-Agent: Safari Chrome" -XGET 'http://127.0.0.1:3333/webp_server.png' -o /dev/null
ls exhaust 
touch pics/webp_server.png 
curl -H "User-Agent: Safari Chrome" -XGET 'http://127.0.0.1:3333/webp_server.png' -o /dev/null
ls exhaust 
```

https://imgur.com/a/kivQ6JQ

**Comment by BlueCocoa** [comment]
It seems that `webpEncoder` somehow changed the underlaying data structure on Linux.

https://imgur.com/download/9idULY4/

## My debugging code

```go
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"image"
	"image/jpeg"
	"image/png"
	"io/ioutil"
	"log"
	"os"
	"path"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/chai2010/webp"
	"github.com/gofiber/fiber"
)

type Config struct {
	HOST         string
	PORT         string
	ImgPath      string `json:"IMG_PATH"`
	QUALITY      string
	AllowedTypes []string `json:"ALLOWED_TYPES"`
}

var configPath string

func webpEncoder(p1, p2 string, quality float32) {
	var buf bytes.Buffer
	var img image.Image
	data, _ := ioutil.ReadFile(p1)
	if strings.Contains(p1, "jpg") || strings.Contains(p1, "jpeg") {
		img, _ = jpeg.Decode(bytes.NewReader(data))
	} else if strings.Contains(p1, "png") {
		img, _ = png.Decode(bytes.NewReader(data))
	}

	if err := webp.Encode(&buf, img, &webp.Options{Lossless: true, Quality: quality}); err != nil {
		log.Println(err)
	}
	if err := ioutil.WriteFile(p2, buf.Bytes(), 0666); err != nil {
		log.Println(err)
	}

	fmt.Println("Save output.webp ok")
}

func init() {
	// Config Here
	flag.StringVar(&configPath, "config", "config.json", "/path/to/config.json. (Default: ./config.json)")
	flag.Parse()
	//flag.PrintDefaults()
}

func main() {
	app := fiber.New()
	app.Banner = false
	app.Server = "WebP Server Go"

	config := load_config(configPath)

	HOST := config.HOST
	PORT := config.PORT
	ImgPath := config.ImgPath
	QUALITY := config.QUALITY
	AllowedTypes := config.AllowedTypes

	ListenAddress := HOST + ":" + PORT

	// Server Info
	ServerInfo := "WebP Server is running at " + ListenAddress
	fmt.Println(ServerInfo)

	app.Get("/*", func(c *fiber.Ctx) {

		// /var/www/IMG_PATH/path/to/tsuki.jpg
		ImgAbsolutePath := ImgPath + c.Path()

		// /path/to/tsuki.jpg
		ImgPath := c.Path()

		// jpg
		seps := strings.Split(path.Ext(ImgPath), ".")
		var ImgExt string
		if len(seps) >= 2 {
			ImgExt = seps[1]
		} else {
			c.Send("Invalid request")
			return
		}

		// tsuki.jpg
		ImgName := path.Base(ImgPath)
		fmt.Println("[1]ImgName:", ImgName)

		// /path/to
		DirPath := path.Dir(ImgPath)

		// 1582558990
		STAT, err := os.Stat(ImgAbsolutePath)
		if err != nil {
			fmt.Println(err.Error())
		}
		ModifiedTime := STAT.ModTime().Unix()

		// /path/to/tsuki.jpg.1582558990.webp
		WebpImgPath := fmt.Sprintf("%s/%s.%d.webp", DirPath, ImgName, ModifiedTime)
		fmt.Println("[2]ImgName:", ImgName)

		// /home/webp_server
		CurrentPath, err := os.Getwd()
		if err != nil {
			fmt.Println(err.Error())
		}

		// /home/webp_server/exhaust/path/to/tsuki.jpg.1582558990.webp
		WebpAbsolutePath := path.Clean(CurrentPath + "/exhaust" + WebpImgPath)

		// /home/webp_server/exhaust/path/to
		DirAbsolutePath := path.Clean(CurrentPath + "/exhaust" + DirPath)

		// Check file extension
		_, found := Find(AllowedTypes, ImgExt)
		if !found {
			c.Send("File extension not allowed!")
			c.SendStatus(403)
			return
		}

		// Check the original image for existence
		if !imageExists(ImgAbsolutePath) {
			// The original image doesn't exist, check the webp image, delete if processed.
			if imageExists(WebpAbsolutePath) {
				os.Remove(WebpAbsolutePath)
			}
			c.Send("File not found!")
			c.SendStatus(404)
			return
		}
		
		// Check for Safari users
		UA := c.Get("User-Agent")
		if strings.Contains(UA, "Safari") && !strings.Contains(UA, "Chrome") && !strings.Contains(UA, "Firefox") {
			c.SendFile(ImgAbsolutePath)
			return
		}
		fmt.Println("[3]ImgName:", ImgName)
		if imageExists(WebpAbsolutePath) {
			c.SendFile(WebpAbsolutePath)
		} else {
			fmt.Println("[4]ImgName:", ImgName)
			// Mkdir
			os.MkdirAll(DirAbsolutePath, os.ModePerm)

			// cwebp -q 60 Cute-Baby-Girl.png -o Cute-Baby-Girl.webp

			q, _ := strconv.ParseFloat(QUALITY, 32)
			webpEncoder(ImgAbsolutePath, WebpAbsolutePath, float32(q))
			if err != nil {
				fmt.Println(err)
			}
			c.SendFile(WebpAbsolutePath)
			
			// /home/webp_server/exhaust/path/to/tsuki.jpg.1582558100.webp <- older ones will be removed
			// /home/webp_server/exhaust/path/to/tsuki.jpg.1582558990.webp <- keep the latest one
			fmt.Println("[5]ImgName:", ImgName)
			WebpCachedImgPath := path.Clean(CurrentPath + "/exhaust" + DirPath + "/" + ImgName + ".*.webp")
			matches, err := filepath.Glob(WebpCachedImgPath)
			if err != nil {
				fmt.Println(err.Error())
			} else {
				for _, path := range matches {
					if strings.Compare(WebpAbsolutePath, path) != 0 {
						os.Remove(path)
					}
				}
			}
		}
	})

	app.Listen(ListenAddress)
}

func load_config(path string) Config {
	var config Config
	jsonObject, err := os.Open(path)
	if err != nil {
		log.Fatal(err)
	}
	defer jsonObject.Close()
	decoder := json.NewDecoder(jsonObject)
	decoder.Decode(&config)
	return config
}

func imageExists(filename string) bool {
	info, err := os.Stat(filename)
	if os.IsNotExist(err) {
		return false
	}
	return !info.IsDir()
}

func Find(slice []string, val string) (int, bool) {
	for i, item := range slice {
		if item == val {
			return i, true
		}
	}
	return -1, false
}
```

**Comment by BlueCocoa** [comment]
Problem solved. For details please see the link below

[记 Golang 下遇到的一回「毫无由头」的内存更改](https://blog.0xbbc.com/2020/02/note-about-encountered-memory-changes-for-no-reason-in-golang/)

**Comment by n0vad3v** [comment]
Nice catch, it's working now. I'm going to merge this PR and do some investigation to our framework later.

Thanks for your awesome work!

**Pull request merged**
